# custom settings are required (not optional)
# always include custom ini files in the fontdir

## igniter settings

# hum will start x milliseconds after ignition begins
# the default is 1000 (any value)

	humstart=1000


## accent swings

# only controls swing responsiveness for legacy fonts
# higher values less responsive - lower values more responsive
# default 250

	ProffieOSSwingSpeedThreshold=250

# used in conjunction with AccentMaxSwingVolume to modulate fade in/out
# the default is 1.0 (0.01 to 2.0)

	ProffieOSSwingVolumeSharpness=0.5

# AccentMaxSwingVolume determines volume peak of fade in/out modulation
# the default is 3.0 x (1.0 to 3.0)

	ProffieOSMaxSwingVolume=2

# introduced to tune spins - allows swing sounds to overlap each other
# to be tuned on a per-font basis
# fonts with lots of silence will need a much lower value
# in order to have good responsiveness
# values range from 0.0 (full overlap) to 1.0 (no overlap)

	ProffieOSSwingOverlap=0.5

# semi-new, reintroduced to deal with fonts that have loud or bass-heavy
# accent swings. This parameter controls how much the volume of smooth
# swing pairs are reduced when an accent swing is playing.
# Values range from 0.0 to 1.0, with 0 meaning no reduction
# and 1 meaning that when the accent swing is at peak volume,
# the smooth swing pairs are totally muted

	ProffieOSSmoothSwingDucking=0.2

# If #define ENABLE_SPINS is defined. Number of degrees the blade must travel while staying above the
# swing threshold in order to trigger a spin sound.  Default is 360 or
# one full rotation.
      

        ProffieOSSpinDegrees=360.0
